version: "3.7"

services:

  dostavimvse:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./scripts/CREATE.sql:/docker-entrypoint-initdb.d/initdb.sql

networks:
  app-network:
    driver: bridge