FROM python:3.6-slim-buster

RUN apt-get update && \
    apt-get install -y cmake build-essential

# Create user 'techproguser' (task 4.b)
RUN useradd -ms /bin/bash techproguser
USER techproguser

WORKDIR /home/techproguser/cmake_with_flask
COPY . .

# Build a cmake project, execute launch by bin/C (task 4.a)
USER root
RUN mkdir build

WORKDIR /home/techproguser/cmake_with_flask/build
RUN cmake build ..
RUN cmake --build .
WORKDIR /home/techproguser/cmake_with_flask
RUN bin/C

# Start the Flask app on port 5000 (task 4.c)
RUN pip3 install -r requirements.txt
EXPOSE 5000
CMD ["python3", "app.py", "--host=0.0.0.0", "--port=5000"]